version: '3'

services:
  idp:
    container_name: idp
    image: ghcr.io/identicum/keycloak:22.0
    restart: always
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./keycloak/:/opt/keycloak/data/import/
    command: "start-dev --import-realm"
  demoapi:
    container_name: demoapi
    image: ghcr.io/identicum/oauth-demoapi-spring:latest
    restart: always
    ports:
      - 8081:8080
    environment:
      ISSUER_URI: http://idp:8080/realms/demorealm
    depends_on:
      idp:
        condition: service_healthy
      