server:
  port: 8081

logging:
  level:
    root: ERROR
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    com.identicum: DEBUG

app:
  scope:
    read: api.identicum.com/product:read
    write: api.identicum.com/product:write

# https://docs.spring.io/spring-security/site/docs/current/reference/html5/#oauth2resourceserver        
spring:
  security:
    oauth2:     
     resourceserver:
# If client_id and client_secret is empty, Spring security uses our 
# custom OpaqueTokenIntrospector implementation to handle token Introspect Bearer authentication
# Otherwise, it uses the default OpaqueTokenIntrospector that supports Basic authentication
       opaquetoken:
#         client-id: ''
#         client-secret: ''
#         introspection-uri: https://gluu.hlgv.net/oxauth/restv1/introspection
        client-id: oauth-demoapi-spring
        client-secret: fb027903-2828-441b-ad1a-26d464a7b770
        introspection-uri: http://host.docker.internal:8090/auth/realms/identicum/protocol/openid-connect/token/introspect